# Generated by Django 2.1 on 2018-08-09 12:41

from django.db import migrations, models
import insecure_app.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, unique=True, verbose_name='Name')),
                ('upload', models.FileField(upload_to=insecure_app.utils.user_directory_path)),
            ],
        ),
    ]
