# Generated by Django 2.1 on 2018-08-09 14:48

from django.db import migrations, models
import insecure_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('insecure_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemedia',
            name='ref',
            field=models.CharField(default=insecure_app.utils.pkgen, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='filemedia',
            name='name',
            field=models.CharField(max_length=7, verbose_name='Name'),
        ),
    ]
