# Generated by Django 2.1 on 2018-08-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('authtoken.token',),
        ),
    ]
